### ISSUE TITLE
Randomization?

### ISSUE THREAD

**Issue by applefatdotgov** [justarandomguyintheinternet/CP77_radioExt#1]
I wanted to go ahead and ask about this, since it's not really listed in the documentation here:
Is there a randomization feature for the track list, or is it simply set up to play one after the other? I'm planning out a very extensive radio mod with 50-100 tracks, including radio DJ barks interspersed, so randomization would be a very benificial thing to have so people don't end up only hearing the first 20 tracks over and over. Would this be best handled via another method than this mod?

**Comment by MG84Flanigan** [comment]
Ummm, I have DJ mixed sets I would like to use and would like to record realistic station ID's and a DJ introducing or recapping songs, but this becomes a big problem when the tracks default to being shuffled. How can we force an order on them?
