### ISSUE TITLE
Crash game after installing

### ISSUE THREAD

**Issue by moooooncrescent** [justarandomguyintheinternet/CP77_radioExt#17]
I am using the latest version of radioext (v.2.3 Patch 2.02 Support)
red4ext 1.20.0
and сet 1.29.1
Game version 2.1

I don't have any other mods. Just installed the mod, did not correct anything in the manifest.json

The game starts and freezes on the logo; when restarting, it prompts you to submit a bug report. Steam version of the game

**Comment by moooooncrescent** [comment]
Tnx for the fix, this update works fine:
https://github.com/justarandomguyintheinternet/CP77_radioExt/releases/tag/v.2.5

**Comment by justarandomguyintheinternet** [comment]
Sorry, I forgot to update the release on GitHub, if in doubt you can always find the latest version on nexus too
