### ISSUE TITLE
File Size

### ISSUE THREAD

**Issue by NateHevens** [justarandomguyintheinternet/CP77_radioExt#2]
I don't know if anyone's even tracking this, but... what happens if I use file-sizes larger than 10mb? I only ask because I want to do a couple radio stations built on full albums... a live show radio and a concept album radio. Maybe this isn't necessary (I don't know if song are randomized or not), but my plan was to turns these albums into a single track before putting them in the radio.

There's no way to get a file that size down to less than 10mb without killing the quality so bad it's unlistenable. Would this still be doable?

Or is this even necessary? Is there a way to force it to play tracks together, as if an entire album is being played rather than just a shuffled list of random songs?

**Comment by justarandomguyintheinternet** [comment]
It'll be fine, the 10mb limit was just a recommendation, as larger files can cause a small delay when being loaded to memory. But nothing technically prevents you from using large files, just give it a try. The next update of the mod (Currently on the /fmod branch will also fix this by not loading the whole audio file into memory at once)
